version: "2"
linters:
  enable:
    - staticcheck
    - unused
  settings:
    errcheck:
      # Exclude functions from error checking
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
        - (net.Listener).Close
        - (*net/http.Response).Body.Close
        - (io.Closer).Close
        - io.Closer.Close
        - fmt.Fprintln
        - fmt.Fprintf
    govet:
      # Disable testinggoroutine for tests calling t.Fatal from goroutines
      disable:
        - testinggoroutine
    staticcheck:
      # Disable checks that were not enforced in v1 configuration
      checks:
        - all
        - "-SA2002"  # t.Fatal in goroutine (same as govet's testinggoroutine)
        - "-SA1019"  # deprecated APIs (existing code, not introduced by this PR)
        - "-SA4006"  # unused value assignments (will fix separately)
        - "-SA4001"  # *&x simplification
        - "-ST1000"  # package comments
        - "-ST1005"  # error string capitalization
        - "-ST1020"  # function comment format
        - "-QF1002"  # tagged switch suggestion
