module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT
// Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

require github.com/jsonnet-bundler/jsonnet-bundler v0.2.0 // cmd/jb
