apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: telemeter-benchmark
  name: telemeter-benchmark
  namespace: telemeter-benchmark
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/name: telemeter-benchmark
