apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: telemeter-benchmark
  name: telemeter-benchmark
  namespace: telemeter-benchmark
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
  jobLabel: k8s-app
  selector:
    matchLabels:
      app.kubernetes.io/name: telemeter-benchmark
