apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: telemetry
  namespace: openshift-monitoring
spec:
  groups:
  - name: telemeter.rules
    rules:
    - expr: max(federate_samples - federate_filtered_samples)
      record: cluster:telemetry_selected_series:count
    - alert: TelemeterClientFailures
      annotations:
        description: |-
          The telemeter client in the namespace {{ $labels.namespace }} fails {{ $value | humanize }} of the requests to the telemeter service.
        summary: Telemeter client fails to send metrics to Red Hat
      expr: |
        sum by (namespace) (
          rate(federate_requests_failed_total{job="telemeter-client"}[15m])
        ) /
        sum by (namespace) (
          rate(federate_requests_total{job="telemeter-client"}[15m])
        ) > 0.2
      for: 1h
      labels:
        severity: warning
